"""
Celery tasks for distributed ingestion.

Task chain for a single document:
  parse_document.s(file_path, doc_meta) | embed_document.s()
  (flush_staged runs on schedule via Celery Beat)
"""
import asyncio
import logging
from typing import Any, Dict, Optional

from backend.ingestion.workers.celery_app import celery_app

logger = logging.getLogger(__name__)


def _run_async(coro):
    """Run an async coroutine from a sync Celery task."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_closed():
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
        return loop.run_until_complete(coro)
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        return loop.run_until_complete(coro)


@celery_app.task(
    bind=True,
    name="backend.ingestion.workers.tasks.parse_document",
    queue="nyaya_parse",
    max_retries=3,
    default_retry_delay=30,
)
def parse_document(
    self,
    file_path: str,
    source_url: Optional[str] = None,
    user_id: Optional[str] = None,
    document_id: Optional[str] = None,
    original_filename: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Stage 1: Parse PDF and write text chunks to PostgreSQL.
    Runs on CPU workers. Returns document_id for embed task.

    document_id can be pre-generated by the caller (e.g. the upload API
    route) so the HTTP response can include a trackable ID immediately,
    instead of the client having no way to know the document_id until
    the whole async chain finishes.
    """
    try:
        from backend.ingestion.parsers.document_parser import DocumentParser
        from backend.ingestion.chunkers.legal_chunker import LegalChunker
        from backend.db.session import get_sync_session
        import uuid
        from sqlalchemy import text

        parser = DocumentParser()
        chunker = LegalChunker()

        parsed = parser.parse(file_path)
        if not parsed.raw_text:
            return {"status": "empty", "file_path": file_path}

        parsed.metadata.source_url = source_url or parsed.metadata.source_url
        document_id = document_id or str(uuid.uuid4())
        parsed.document_id = document_id
        parsed.metadata.document_id = document_id

        chunks = chunker.chunk(parsed)
        if not chunks:
            return {"status": "no_chunks", "document_id": document_id}

        # Bulk insert via a single execute() call with a list of param dicts
        # instead of one INSERT per chunk in a Python loop — a document with
        # thousands of chunks previously did thousands of DB round-trips
        # here even though this exact bug was already fixed in
        # ingest.py's _write_chunks_to_db; this Celery path had drifted
        # back to the slow pattern independently.
        with get_sync_session() as db:
            db.execute(text("""
                INSERT INTO documents (
                    document_id, document_type, law, court, court_name,
                    citation, year, source_url, original_filename,
                    is_landmark, language, pages, uploaded_by, created_at
                ) VALUES (
                    :doc_id, :doc_type, :law, :court, :court_name,
                    :citation, :year, :source_url, :original_filename,
                    false, :language, :pages, :uploaded_by, NOW()
                ) ON CONFLICT (document_id) DO NOTHING
            """), {
                "doc_id": document_id,
                "doc_type": parsed.metadata.document_type.value,
                "law": parsed.metadata.law.value if parsed.metadata.law else None,
                "court": parsed.metadata.court.value if parsed.metadata.court else None,
                "court_name": parsed.metadata.court_name,
                "citation": parsed.metadata.citation,
                "year": parsed.metadata.year,
                "source_url": parsed.metadata.source_url,
                "original_filename": original_filename,
                "language": parsed.metadata.language,
                "pages": parsed.pages,
                "uploaded_by": user_id,
            })

            law_val = parsed.metadata.law.value if parsed.metadata.law else "other"
            chunk_rows = [{
                "chunk_id": c.chunk_id, "document_id": document_id,
                "chunk_type": c.chunk_type.value, "content": c.content,
                "content_length": c.content_length, "chunk_index": c.chunk_index,
                "page_number": c.page_number, "section_ref": c.section_ref,
                "subsection_ref": c.subsection_ref, "law": law_val,
            } for c in chunks]

            INSERT_SQL = text("""
                INSERT INTO chunks (
                    chunk_id, document_id, chunk_type, content,
                    content_length, chunk_index, page_number,
                    section_ref, subsection_ref, law, content_tsv
                ) VALUES (
                    :chunk_id, :document_id, :chunk_type, :content,
                    :content_length, :chunk_index, :page_number,
                    :section_ref, :subsection_ref, :law,
                    to_tsvector('english', :content)
                ) ON CONFLICT (chunk_id, law) DO NOTHING
            """)
            BATCH = 2000
            for i in range(0, len(chunk_rows), BATCH):
                db.execute(INSERT_SQL, chunk_rows[i:i + BATCH])
            db.commit()

        logger.info(f"Parsed {len(chunks)} chunks → document_id={document_id}")
        return {
            "status": "parsed",
            "document_id": document_id,
            "chunk_ids": [c.chunk_id for c in chunks],
            "chunk_contents": {c.chunk_id: c.content for c in chunks},
            "chunk_payloads": {
                c.chunk_id: {
                    "chunk_id": c.chunk_id,
                    "document_id": document_id,
                    "chunk_type": c.chunk_type.value,
                    "content": c.content,
                    "content_length": c.content_length,
                    "chunk_index": c.chunk_index,
                    "page_number": c.page_number,
                    "section_ref": c.section_ref,
                    "document_type": parsed.metadata.document_type.value,
                    "law": parsed.metadata.law.value if parsed.metadata.law else None,
                    "court": parsed.metadata.court.value if parsed.metadata.court else None,
                    "court_name": parsed.metadata.court_name,
                    "citation": parsed.metadata.citation,
                    "year": parsed.metadata.year,
                    "source_url": parsed.metadata.source_url,
                    "is_landmark": False,
                    "language": parsed.metadata.language,
                }
                for c in chunks
            },
        }
    except Exception as exc:
        logger.error(f"parse_document failed for {file_path}: {exc}")
        raise self.retry(exc=exc)


@celery_app.task(
    bind=True,
    name="backend.ingestion.workers.tasks.embed_document",
    queue="nyaya_parse",   # runs on CPU — just fans out sub-tasks, no GPU needed
    max_retries=3,
    default_retry_delay=60,
    time_limit=120,
)
def embed_document(self, parse_result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Stage 2: Fan out embedding across 4 GPU workers.

    Instead of one embed task processing all chunks sequentially on a
    single GPU (bottleneck: a 10K-chunk document takes ~20 seconds even
    on a fast GPU), this task splits the chunk list into sub-batches of
    embed_subtask_size (512) and dispatches each sub-batch to a GPU
    queue, cycling round-robin across all 4 GPU queues.

    Result: a 10K-chunk document fans into 20 sub-tasks. With 4 GPU
    workers running in parallel, wall time drops from ~20s to ~5s.
    A 50K-chunk document fans into 98 sub-tasks → ~25s vs ~100s.

    The sub-tasks write independently to staged_chunks; flush_staged
    picks them up as they land, so Qdrant indexing and embedding
    overlap in time rather than waiting for the full document.
    """
    if parse_result.get("status") != "parsed":
        return parse_result

    document_id = parse_result["document_id"]
    chunk_ids: List[str] = parse_result["chunk_ids"]
    contents: Dict[str, str] = parse_result["chunk_contents"]
    payloads: Dict[str, Any] = parse_result["chunk_payloads"]

    try:
        from backend.config.settings import get_settings
        from backend.ingestion.workers.celery_app import GPU_EMBED_QUEUES

        subtask_size = get_settings().ingestion.embed_subtask_size
        gpu_count = len(GPU_EMBED_QUEUES)
        sub_results = []

        for i, start in enumerate(range(0, len(chunk_ids), subtask_size)):
            batch_ids = chunk_ids[start:start + subtask_size]
            batch_contents = {cid: contents[cid] for cid in batch_ids}
            batch_payloads = {cid: payloads[cid] for cid in batch_ids}
            target_queue = GPU_EMBED_QUEUES[i % gpu_count]

            result = embed_chunk_batch.apply_async(
                kwargs={
                    "document_id": document_id,
                    "chunk_ids": batch_ids,
                    "chunk_contents": batch_contents,
                    "chunk_payloads": batch_payloads,
                },
                queue=target_queue,
            )
            sub_results.append(result.id)

        logger.info(
            f"embed_document fanned {len(chunk_ids)} chunks into "
            f"{len(sub_results)} sub-tasks across {gpu_count} GPU queues "
            f"for document {document_id}"
        )
        return {
            "status": "embedding",
            "document_id": document_id,
            "subtask_ids": sub_results,
            "total_chunks": len(chunk_ids),
        }
    except Exception as exc:
        logger.error(f"embed_document fan-out failed for {document_id}: {exc}")
        raise self.retry(exc=exc)


@celery_app.task(
    bind=True,
    name="backend.ingestion.workers.tasks.embed_chunk_batch",
    max_retries=3,
    default_retry_delay=30,
    time_limit=300,
    # queue is NOT set here — the caller specifies which GPU queue to use
    # via apply_async(queue=target_queue). Celery routes to that queue;
    # the worker consuming it has CUDA_VISIBLE_DEVICES set to its GPU.
)
def embed_chunk_batch(
    self,
    document_id: str,
    chunk_ids: List[str],
    chunk_contents: Dict[str, str],
    chunk_payloads: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Embed one sub-batch of chunks on a single GPU worker.

    Called by embed_document fan-out. Each worker has CUDA_VISIBLE_DEVICES
    set to exactly one GPU, so EmbeddingService.embed_batch_sync() always
    runs on that worker's assigned card.
    """
    try:
        from backend.embeddings.service import EmbeddingService
        from backend.db.session import get_sync_session
        from sqlalchemy import text
        import json as _json

        embedder = EmbeddingService()
        texts = [chunk_contents[cid] for cid in chunk_ids]
        embeddings = embedder.embed_batch_sync(texts)

        # Batch insert to staging — one executemany call, not N individual inserts
        rows = [
            {
                "chunk_id": cid,
                "document_id": document_id,
                "embedding": _json.dumps(emb),
                "meta": _json.dumps(chunk_payloads.get(cid, {})),
            }
            for cid, emb in zip(chunk_ids, embeddings)
        ]

        with get_sync_session() as db:
            db.execute(text("""
                INSERT INTO staged_chunks
                    (chunk_id, document_id, embedding, metadata, indexed)
                VALUES (:chunk_id, :document_id, :embedding::vector, :meta::jsonb, false)
                ON CONFLICT (chunk_id) DO NOTHING
            """), rows)
            db.commit()

        logger.info(
            f"embed_chunk_batch: {len(chunk_ids)} chunks → staging "
            f"(document={document_id})"
        )
        return {"status": "embedded", "document_id": document_id, "count": len(chunk_ids)}

    except Exception as exc:
        logger.error(f"embed_chunk_batch failed for {document_id}: {exc}")
        raise self.retry(exc=exc)


@celery_app.task(
    name="backend.ingestion.workers.tasks.dead_letter_handler",
    queue="nyaya_dlq",
)
def dead_letter_handler(task_name: str, task_args: Any, task_kwargs: Any, exc: str) -> None:
    """
    Receives tasks that exhausted all retries.
    Logs them for manual inspection — run:
        celery -A backend.ingestion.workers.celery_app inspect reserved
    or query the Redis DLQ directly.
    """
    logger.error(
        f"DEAD LETTER: task={task_name} failed permanently. "
        f"exc={exc} kwargs={str(task_kwargs)[:500]}"
    )


@celery_app.task(
    name="backend.ingestion.workers.tasks.flush_staged",
    queue="nyaya_flush",
)
def flush_staged() -> Dict[str, Any]:
    """
    Stage 3 (scheduled every INGEST_FLUSH_INTERVAL_S seconds via Celery Beat):
    Atomically claim a batch of unindexed staged chunks, upsert them to
    Qdrant, then mark them indexed.

    Key design decisions vs the original:
    1. SELECT ... WHERE processing=false FOR UPDATE SKIP LOCKED:
       Atomically marks rows as 'processing=true' before reading them.
       If two flush_staged tasks overlap (e.g. a previous tick's Qdrant
       write was slow), SKIP LOCKED ensures the second task processes
       a DIFFERENT batch rather than re-attempting the same rows —
       previously both tasks would fetch the same rows, causing duplicate
       Qdrant upserts and wasted work.
    2. asyncio.run() instead of asyncio.new_event_loop() + loop.close():
       The old pattern leaked OS threads on Python 3.11 because closing
       a loop without draining shutdown_asyncgens left finalizer tasks
       hanging. asyncio.run() handles full cleanup.
    3. cursor-based ordering (created_at, chunk_id) instead of LIMIT-only:
       LIMIT N with no ORDER BY is non-deterministic — the DB can return
       different row sets across ticks. Ordered by created_at ensures
       oldest chunks are flushed first (FIFO ingestion order).
    4. DELETE instead of UPDATE indexed=true: removes flushed rows to
       keep staged_chunks lean. The source of truth is Qdrant; keeping
       successfully indexed rows in staging is pure waste.
    """
    import asyncio

    try:
        from backend.db.session import get_sync_session
        from backend.retrieval.vector.retriever import VectorRetriever
        from backend.config.settings import get_settings
        from sqlalchemy import text

        cfg = get_settings().ingestion
        vector = VectorRetriever()

        # Step 1: atomically claim a batch
        with get_sync_session() as db:
            # Mark rows as processing=true in one UPDATE...RETURNING so no
            # other flush worker (or next tick) can claim the same rows.
            claimed = db.execute(text("""
                UPDATE staged_chunks
                SET    processing = true
                WHERE  chunk_id IN (
                    SELECT chunk_id
                    FROM   staged_chunks
                    WHERE  indexed = false AND processing = false
                    ORDER  BY created_at, chunk_id
                    LIMIT  :batch
                    FOR UPDATE SKIP LOCKED
                )
                RETURNING chunk_id, embedding, metadata
            """), {"batch": cfg.flush_batch_size}).fetchall()
            db.commit()

        if not claimed:
            return {"status": "nothing_to_flush"}

        chunk_ids = [str(r.chunk_id) for r in claimed]
        # embedding stored as JSONB → comes back as a Python list directly
        vectors   = [r.embedding for r in claimed]
        payloads  = [dict(r.metadata) for r in claimed]

        # Step 2: upsert to Qdrant (async, non-blocking)
        success = asyncio.run(
            vector.upsert_batch(chunk_ids, vectors, payloads, wait=False)
        )

        # Step 3: mark as indexed OR release the processing lock on failure
        with get_sync_session() as db:
            if success:
                # Delete flushed rows — Qdrant is now the source of truth.
                # Keeping them as indexed=true wastes storage and slows scans.
                db.execute(text("""
                    DELETE FROM staged_chunks WHERE chunk_id = ANY(:ids)
                """), {"ids": chunk_ids})
            else:
                # Release lock so the next tick can retry
                db.execute(text("""
                    UPDATE staged_chunks SET processing = false
                    WHERE chunk_id = ANY(:ids)
                """), {"ids": chunk_ids})
            db.commit()

        logger.info(
            f"flush_staged: {'indexed' if success else 'FAILED'} "
            f"{len(chunk_ids)} chunks to Qdrant"
        )
        return {"status": "flushed" if success else "failed", "count": len(chunk_ids)}

    except Exception as e:
        logger.error(f"flush_staged crashed: {e}", exc_info=True)
        # Best-effort: release processing locks so rows aren't stuck forever
        try:
            from backend.db.session import get_sync_session
            from sqlalchemy import text
            with get_sync_session() as db:
                db.execute(text(
                    "UPDATE staged_chunks SET processing = false WHERE processing = true"
                ))
                db.commit()
        except Exception:
            pass
        return {"status": "error", "error": str(e)}
